### ISSUE TITLE
Unable to create project using composer

### ISSUE THREAD

**Issue by realmrv** [yiisoft/yii-base-cli#8]
When creating a project, the installation of packages falls on the `yiisoft/inflector` package. I get the message `ERROR: Repository not found`. And yes, that’s true.

If possible, please update the package set of this cli application template.

**Comment by samdark** [comment]
For now start with https://github.com/yiisoft/yii-demo

**Comment by realmrv** [comment]
I did not immediately understand the purpose of this project, but I already figured it out. Thank.
